// =============================================================================
// Auto-generated cfg package -- DO NOT EDIT
// Generated by tools/cfg2sv.py
// =============================================================================

`ifndef SSV_CFG_PKG_SV
`define SSV_CFG_PKG_SV

package ssv_cfg_pkg;

  // cfg classes extend ssv_pkg::ssv_object
  `include "uvm_macros.svh"
  import uvm_pkg::*;
  import ssv_pkg::*;

  // One .sv per cfg class, sitting next to its .cfg source (so the
  // .cfg + .sv pair can be copied together).
  `include "sub_agent.sv"
  `include "top.sv"

endpackage

`endif // SSV_CFG_PKG_SV