// =============================================================================
// Auto-generated from sub_agent.cfg -- DO NOT EDIT
// Generated by tools/cfg2sv.py
// =============================================================================

class sub_agent_cfg extends ssv_object;

  rand int AGENT_ID = 0;
  rand bit IS_ACTIVE = 1'b1;
  rand int ADDR_WIDTH = 32;
  rand int DATA_WIDTH = 64;
  string NAME = "sub_agent_default";
  real TURN_AROUND = 0.0;

  `uvm_object_utils_begin(sub_agent_cfg)
    `uvm_field_int(AGENT_ID, UVM_DEFAULT)
    `uvm_field_int(IS_ACTIVE, UVM_DEFAULT)
    `uvm_field_int(ADDR_WIDTH, UVM_DEFAULT)
    `uvm_field_int(DATA_WIDTH, UVM_DEFAULT)
    `uvm_field_string(NAME, UVM_DEFAULT)
    `uvm_field_real(TURN_AROUND, UVM_DEFAULT)
  `uvm_object_utils_end

  function new(string name = "sub_agent_cfg");
    super.new(name);
  endfunction

  function bit apply_field(string field_name, string value);
    bit applied = 0;
    case (field_name)
      "AGENT_ID": begin AGENT_ID = ssv_object::ssv_atoi(value); applied = 1; end
      "IS_ACTIVE": begin IS_ACTIVE = ssv_object::ssv_atoi(value); applied = 1; end
      "ADDR_WIDTH": begin ADDR_WIDTH = ssv_object::ssv_atoi(value); applied = 1; end
      "DATA_WIDTH": begin DATA_WIDTH = ssv_object::ssv_atoi(value); applied = 1; end
      "NAME": begin NAME = ssv_object::ssv_unquote(value); applied = 1; end
      "TURN_AROUND": begin TURN_AROUND = value.atoreal(); applied = 1; end
      default: ;
    endcase
    return applied;
  endfunction

  function ssv_object find_sub(string inst_name);
    return null;
  endfunction

endclass
