// =============================================================================
// Auto-generated from top.cfg -- DO NOT EDIT
// Generated by tools/cfg2sv.py
// =============================================================================

class ssv_root_cfg extends ssv_object;

  rand int unsigned NUM_AGENTS = 2;
  rand bit ENABLE_LOG = 1'b1;
  rand bit ENABLE_CHECKER = 1'b0;
  string ENV_NAME = "ssv_default";
  string DEFAULT_SEED = "no_seed";
  real CLK_PERIOD_NS = 10.0;
  int MY_DYN_ARR [] = '{};
  int MY_QUEUE [$] = '{};
  string NAMES [] = '{};
  string NAMES_Q [] = '{};
  int COUNTERS [] = ' { 1 , 2 , 3 };
  sub_agent_cfg agent_a;
  sub_agent_cfg agent_b;

  `uvm_object_utils_begin(ssv_root_cfg)
    `uvm_field_int(NUM_AGENTS, UVM_DEFAULT)
    `uvm_field_int(ENABLE_LOG, UVM_DEFAULT)
    `uvm_field_int(ENABLE_CHECKER, UVM_DEFAULT)
    `uvm_field_string(ENV_NAME, UVM_DEFAULT)
    `uvm_field_string(DEFAULT_SEED, UVM_DEFAULT)
    `uvm_field_real(CLK_PERIOD_NS, UVM_DEFAULT)
    `uvm_field_array_int(MY_DYN_ARR, UVM_DEFAULT)
    `uvm_field_queue_int(MY_QUEUE, UVM_DEFAULT)
    `uvm_field_array_string(NAMES, UVM_DEFAULT)
    `uvm_field_array_string(NAMES_Q, UVM_DEFAULT)
    `uvm_field_array_int(COUNTERS, UVM_DEFAULT)
    `uvm_field_object(agent_a, UVM_DEFAULT)
    `uvm_field_object(agent_b, UVM_DEFAULT)
  `uvm_object_utils_end

  function new(string name = "ssv_root_cfg");
    super.new(name);
    agent_a = sub_agent_cfg::type_id::create("agent_a");
    agent_a.AGENT_ID = 0;
    agent_a.IS_ACTIVE = 1'b1;
    agent_a.ADDR_WIDTH = 32;
    agent_a.DATA_WIDTH = 64;
    agent_b = sub_agent_cfg::type_id::create("agent_b");
    agent_b.AGENT_ID = 1;
    agent_b.IS_ACTIVE = 1'b0;
    agent_b.ADDR_WIDTH = 16;
    agent_b.DATA_WIDTH = 32;
  endfunction

  function bit apply_field(string field_name, string value);
    bit applied = 0;
    case (field_name)
      "NUM_AGENTS": begin NUM_AGENTS = ssv_object::ssv_atoi(value); applied = 1; end
      "ENABLE_LOG": begin ENABLE_LOG = ssv_object::ssv_atoi(value); applied = 1; end
      "ENABLE_CHECKER": begin ENABLE_CHECKER = ssv_object::ssv_atoi(value); applied = 1; end
      "ENV_NAME": begin ENV_NAME = ssv_object::ssv_unquote(value); applied = 1; end
      "DEFAULT_SEED": begin DEFAULT_SEED = ssv_object::ssv_unquote(value); applied = 1; end
      "CLK_PERIOD_NS": begin CLK_PERIOD_NS = value.atoreal(); applied = 1; end
      "MY_QUEUE": begin MY_QUEUE.push_back(ssv_object::ssv_atoi(value)); applied = 1; end
      default: ;
    endcase
    if (!applied) applied = apply_array_field(field_name, value);
    return applied;
  endfunction

  // apply_array_field: handle the 'FIELD.size' (resize) and
  // 'FIELD[N]' (write the Nth element, auto-grow) modifier forms
  // for dynamic-array field names.
  function bit apply_array_field(string field_name, string value);
    bit applied = 0;
    string base;
    int    idx;

    // 'FIELD[N]' form: write element by index.
    if (ssv_object::ssv_match_array_idx(field_name, base, idx)) begin
      case (base)
        "MY_DYN_ARR": begin
          if (MY_DYN_ARR.size <= idx) MY_DYN_ARR = new[idx+1];
          MY_DYN_ARR[idx] = ssv_object::ssv_atoi(value);
          applied = 1;
        end
        "NAMES": begin
          if (NAMES.size <= idx) NAMES = new[idx+1];
          NAMES[idx] = ssv_object::ssv_unquote(value);
          applied = 1;
        end
        "NAMES_Q": begin
          if (NAMES_Q.size <= idx) NAMES_Q = new[idx+1];
          NAMES_Q[idx] = ssv_object::ssv_unquote(value);
          applied = 1;
        end
        "COUNTERS": begin
          if (COUNTERS.size <= idx) COUNTERS = new[idx+1];
          COUNTERS[idx] = ssv_object::ssv_atoi(value);
          applied = 1;
        end
        default: ;
      endcase
    end
    if (applied) return applied;

    // 'FIELD.size' form: resize (old elements are discarded).
    if (ssv_object::ssv_match_field_size(field_name, base)) begin
      case (base)
        "MY_DYN_ARR": begin MY_DYN_ARR = new[ssv_object::ssv_atoi(value)]; applied = 1; end
        "NAMES": begin NAMES = new[ssv_object::ssv_atoi(value)]; applied = 1; end
        "NAMES_Q": begin NAMES_Q = new[ssv_object::ssv_atoi(value)]; applied = 1; end
        "COUNTERS": begin COUNTERS = new[ssv_object::ssv_atoi(value)]; applied = 1; end
        default: ;
      endcase
    end
    return applied;
  endfunction

  function ssv_object find_sub(string inst_name);
    case (inst_name)
      "agent_a": return agent_a;
      "agent_b": return agent_b;
      default: return null;
    endcase
  endfunction

endclass
