// =============================================================================
// my_min_test.sv - minimal smoke: no env built; only verifies that the ssv
// dispatcher wrote the hierarchy overrides from cfg.info into root_cfg
// (cfg.info is generated by Python from cases/<x>.cmd after expansion).
// =============================================================================
`ifndef MY_MIN_TEST_SV
`define MY_MIN_TEST_SV

package my_min_test_pkg;

  `include "uvm_macros.svh"
  import uvm_pkg::*;
  import ssv_pkg::*;
  import ssv_cfg_pkg::*;

  class my_min_test extends uvm_test;

    `uvm_component_utils(my_min_test)

    ssv_object    root_cfg;
    ssv_root_cfg  my_root;

    function new(string name = "my_min_test", uvm_component parent = null);
      super.new(name, parent);
    endfunction

    virtual function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      root_cfg = ssv_root_cfg::type_id::create("ssv_root_cfg");
      void'($cast(my_root, root_cfg));

      ssv_object::apply_overrides_in_cwd(root_cfg);
    endfunction

    virtual task main_phase(uvm_phase phase);
      phase.raise_objection(this);
      `uvm_info("MY_MIN_TEST",
        $sformatf("cfg dump: NUM_AGENTS=%0d ENV=%s agent_a.NAME=%s agent_b.ADDR_WIDTH=%0d",
                  my_root.NUM_AGENTS, my_root.ENV_NAME,
                  my_root.agent_a.NAME, my_root.agent_b.ADDR_WIDTH), UVM_LOW)
      #10ns;
      phase.drop_objection(this);
    endtask

  endclass

endpackage

`endif // MY_MIN_TEST_SV