// =============================================================================
// my_test.sv - user example test (extends uvm_test directly)
//
// Demonstrates core ssv usage:
//   1. Construct the root cfg (ssv_root_cfg generated by cfg2sv)
//   2. Call ssv_object::apply_overrides_in_cwd(root_cfg)
//      — internally it opens the relative path "cfg.info" (relies on
//      cwd = case run dir, set by Python run_case.py). cfg.info is
//      generated by Python from the ssv_cfg: lines in cases/<case>.cmd
//      after fnmatch globs are expanded.
//   3. Inject the cfg into env
// =============================================================================
`ifndef MY_TEST_SV
`define MY_TEST_SV

package my_test_pkg;

  `include "uvm_macros.svh"
  import uvm_pkg::*;
  import ssv_pkg::*;
  import ssv_cfg_pkg::*;
  import my_env_pkg::*;

  class my_test extends uvm_test;

    `uvm_component_utils(my_test)

    my_env      env;
    ssv_object  root_cfg;
    ssv_root_cfg my_root;

    function new(string name = "my_test", uvm_component parent = null);
      super.new(name, parent);
    endfunction

    virtual function void build_phase(uvm_phase phase);
      super.build_phase(phase);

      root_cfg = ssv_root_cfg::type_id::create("ssv_root_cfg");
      if (!$cast(my_root, root_cfg))
        `uvm_fatal("MY_TEST", "root_cfg not ssv_root_cfg")

      // ★ ssv's only public entry point: opens the relative path "cfg.info"
      //   (relies on cwd = case run dir, set by Python run_case.py).
      ssv_object::apply_overrides_in_cwd(root_cfg);

      uvm_config_db#(ssv_object)::set(null, "uvm_test_top.env", "cfg", root_cfg);

      env = my_env::type_id::create("env", this);
    endfunction

    virtual task main_phase(uvm_phase phase);
      phase.raise_objection(this);
	  $display("main_phase");
      `uvm_info("MY_TEST",
        $sformatf("running with NUM_AGENTS=%0d ENV=%s",
                  my_root.NUM_AGENTS, my_root.ENV_NAME),
        UVM_LOW)
      // dyn-array / queue dump (guard with size to avoid out-of-range)
      `uvm_info("MY_TEST",
        $sformatf("MY_DYN_ARR: size=%0d%s%s%s",
                  my_root.MY_DYN_ARR.size(),
                  my_root.MY_DYN_ARR.size() > 0 ? $sformatf(" [0]=%0d", my_root.MY_DYN_ARR[0]) : "",
                  my_root.MY_DYN_ARR.size() > 1 ? $sformatf(" [1]=%0d", my_root.MY_DYN_ARR[1]) : "",
                  my_root.MY_DYN_ARR.size() > 2 ? $sformatf(" [2]=%0d", my_root.MY_DYN_ARR[2]) : ""),
        UVM_LOW)
      `uvm_info("MY_TEST",
        $sformatf("MY_QUEUE: size=%0d%s%s%s",
                  my_root.MY_QUEUE.size(),
                  my_root.MY_QUEUE.size() > 0 ? $sformatf(" [0]=%0d", my_root.MY_QUEUE[0]) : "",
                  my_root.MY_QUEUE.size() > 1 ? $sformatf(" [1]=%0d", my_root.MY_QUEUE[1]) : "",
                  my_root.MY_QUEUE.size() > 2 ? $sformatf(" [2]=%0d", my_root.MY_QUEUE[2]) : ""),
        UVM_LOW)
      `uvm_info("MY_TEST",
        $sformatf("NAMES: size=%0d%s%s",
                  my_root.NAMES.size(),
                  my_root.NAMES.size() > 0 ? $sformatf(" [0]=%0s", my_root.NAMES[0]) : "",
                  my_root.NAMES.size() > 1 ? $sformatf(" [1]=%0s", my_root.NAMES[1]) : ""),
        UVM_LOW)
      `uvm_info("MY_TEST",
        $sformatf("NAMES_Q: size=%0d%s%s",
                  my_root.NAMES_Q.size(),
                  my_root.NAMES_Q.size() > 0 ? $sformatf(" [0]=%0s", my_root.NAMES_Q[0]) : "",
                  my_root.NAMES_Q.size() > 1 ? $sformatf(" [1]=%0s", my_root.NAMES_Q[1]) : ""),
        UVM_LOW)
      `uvm_info("MY_TEST",
        $sformatf("COUNTERS (default): size=%0d [0]=%0d [1]=%0d [2]=%0d",
                  my_root.COUNTERS.size(),
                  my_root.COUNTERS[0], my_root.COUNTERS[1], my_root.COUNTERS[2]),
        UVM_LOW)
      #100ns;
      phase.drop_objection(this);
    endtask

  endclass

endpackage

`endif // MY_TEST_SV