# Auto-generated default cfg dump. Each line: ssv_cfg: <hierarchy> = <value>
# Generated by tools/cfg2sv.py

ssv_cfg: ssv_root_cfg.NUM_AGENTS = 2
ssv_cfg: ssv_root_cfg.ENABLE_LOG = 1'b1
ssv_cfg: ssv_root_cfg.ENABLE_CHECKER = 1'b0
ssv_cfg: ssv_root_cfg.ENV_NAME = "ssv_default"
ssv_cfg: ssv_root_cfg.DEFAULT_SEED = "no_seed"
ssv_cfg: ssv_root_cfg.CLK_PERIOD_NS = 10.0
ssv_cfg: ssv_root_cfg.MY_DYN_ARR = '{}
ssv_cfg: ssv_root_cfg.MY_QUEUE = '{}
ssv_cfg: ssv_root_cfg.NAMES = '{}
ssv_cfg: ssv_root_cfg.NAMES_Q = '{}
ssv_cfg: ssv_root_cfg.COUNTERS = ' { 1 , 2 , 3 }
ssv_cfg: ssv_root_cfg.agent_a.AGENT_ID = 0
ssv_cfg: ssv_root_cfg.agent_a.IS_ACTIVE = 1'b1
ssv_cfg: ssv_root_cfg.agent_a.ADDR_WIDTH = 32
ssv_cfg: ssv_root_cfg.agent_a.DATA_WIDTH = 64
ssv_cfg: ssv_root_cfg.agent_a.NAME = "sub_agent_default"
ssv_cfg: ssv_root_cfg.agent_a.TURN_AROUND = 0.0
ssv_cfg: ssv_root_cfg.agent_b.AGENT_ID = 1
ssv_cfg: ssv_root_cfg.agent_b.IS_ACTIVE = 1'b0
ssv_cfg: ssv_root_cfg.agent_b.ADDR_WIDTH = 16
ssv_cfg: ssv_root_cfg.agent_b.DATA_WIDTH = 32
ssv_cfg: ssv_root_cfg.agent_b.NAME = "sub_agent_default"
ssv_cfg: ssv_root_cfg.agent_b.TURN_AROUND = 0.0
