// =============================================================================
// ssv_object.sv - Base class for every cfg parameter object (ssv core).
//
// Responsibilities:
//   - Inherits from uvm_object and provides a single field-override entry point.
//   - Each concrete cfg class generated by cfg2sv.py overrides apply_field /
//     find_sub.
//   - Provides dispatch_path: walk the hierarchy path and dispatch the
//     override all the way down to the leaf.
//
// This is the only ssv file that cannot be omitted.
//
// Runtime flow:
//   1. tools/run_case.py writes cfg.info into the case run dir
//      (sim/<variant>/run/<case>/) -- ssv_cfg: lines extracted from
//      cases/<case>.cmd with globs pre-expanded by Python's fnmatch.
//   2. run_case.py sets the simv process's cwd to that case run dir
//      (the same dir as cfg.info).
//   3. After simv starts, the test's build_phase calls
//      apply_overrides_in_cwd(root_cfg).
//   4. This class opens the relative path "cfg.info" (relies on
//      cwd == case run dir).
//   5. For every "ssv_cfg: <path> = <val>" line we split <path> on '.'
//      and feed the resulting token queue into dispatch_path.
//   6. The SV side does NOT read cases/*.cmd, env vars, plusargs, or do
//      any glob expansion -- it only consumes cfg.info.
// =============================================================================
`ifndef SSV_OBJECT_SV
`define SSV_OBJECT_SV

virtual class ssv_object extends uvm_object;

  function new(string name = "ssv_object");
    super.new(name);
  endfunction

  // Apply a single field-level override on this object.
  pure virtual function bit apply_field(string field_name, string value);

  // Find a sub-object (declared in this cfg class) by instance name.
  pure virtual function ssv_object find_sub(string inst_name);

  // --------------------------------------------------------------------
  // dispatch_path: if the head token names a sub-object, recurse;
  // otherwise treat the head as a field name on this object.
  // If the head is not a sub-object and the path still has more tokens,
  // we fall back to a "field-name with suffix" form (e.g. for
  // 'DYN_ARR.size' / 'DYN_ARR[0]': the remainder is joined back with
  // '.' and apply_field handles the dynamic-array modifier form).
  // --------------------------------------------------------------------
  function void dispatch_path(string path_q[$], string value);
    string head;
    ssv_object sub;
    string full_name;
    if (path_q.size() == 0) return;

    head = path_q[0];
    path_q.pop_front();

    sub = find_sub(head);
    if (sub != null) begin
      sub.dispatch_path(path_q, value);
      return;
    end

    if (path_q.size() == 0) begin
      if (!apply_field(head, value))
        `uvm_warning("SSV_CFG",
          $sformatf("%s: unknown field '%s' (value='%s')", get_name(), head, value))
    end else begin
      // Head is not a sub-object -- try the "field-name with suffix" form
      // (dynamic-array .size / [N]).
      full_name = head;
      while (path_q.size() > 0) begin
        full_name = {full_name, ".", path_q[0]};
        path_q.pop_front();
      end
      if (!apply_field(full_name, value))
        `uvm_warning("SSV_CFG",
          $sformatf("%s: unknown field '%s' (value='%s')", get_name(), full_name, value))
    end
  endfunction

  // --------------------------------------------------------------------
  // ssv_match_array_idx: parse the "BASE[IDX]" form.
  //   Match:    returns 1, base=field name, idx=parsed integer.
  //   No match: returns 0, base="", idx=0.
  // --------------------------------------------------------------------
  static function bit ssv_match_array_idx(string name, output string base, output int idx);
    int bracket_pos;
    int i;
    string num_str;
    base = "";
    idx  = 0;
    bracket_pos = -1;
    for (i = 0; i < name.len(); i++) begin
      if (name[i] == "[") begin
        bracket_pos = i;
        break;
      end
    end
    if (bracket_pos <= 0) return 0;
    if (name[name.len()-1] != "]") return 0;
    base = name.substr(0, bracket_pos-1);
    num_str = name.substr(bracket_pos+1, name.len()-2);
    idx = ssv_atoi(num_str);
    return 1;
  endfunction

  // --------------------------------------------------------------------
  // ssv_match_field_size: parse the "BASE.size" form.
  //   Match:    returns 1, base=field name.
  //   No match: returns 0, base="".
  // --------------------------------------------------------------------
  static function bit ssv_match_field_size(string name, output string base);
    int dot_pos;
    int i;
    string suffix;
    base = "";
    dot_pos = -1;
    for (i = name.len()-1; i >= 0; i--) begin
      if (name[i] == ".") begin
        dot_pos = i;
        break;
      end
    end
    if (dot_pos <= 0) return 0;
    suffix = name.substr(dot_pos+1, name.len()-1);
    if (suffix != "size") return 0;
    base = name.substr(0, dot_pos-1);
    return 1;
  endfunction

  // --------------------------------------------------------------------
  // apply_overrides_from_file: read cfg.info (or any .cfg-shaped file).
  //   Every "ssv_cfg: <hierarchy> = <value>" line goes through dispatch_path
  //   on root.
  //
  // cfg.info is generated by Python run_case.py in the case run dir (with
  // globs already expanded); this function only parses the ssv_cfg: line
  // into hierarchy + value -- it does NOT read all.cmd or do any glob
  // expansion.
  // --------------------------------------------------------------------
  static function void apply_overrides_from_file(ssv_object root, string filename);
    int fd;
    int dummy;
    string line;
    string prefix;
    string parts[$];
    int    pi;
    int    pstart;
    string body;
    int    eq;
    string path;
    string val;
    string root_name;
    int    keep;
    int    i;
    if (root == null) begin
      `uvm_error("SSV_CFG", "apply_overrides_from_file called with null root")
      return;
    end
    fd = $fopen(filename, "r");
    if (fd == 0) begin
      `uvm_warning("SSV_CFG", $sformatf("cannot open cfg file '%s'", filename))
      return;
    end

    prefix = "ssv_cfg:";
    while (!$feof(fd)) begin
      // Reset parts for each line.
      parts = {};
      dummy = $fgets(line, fd);
      line = ssv_str_chomp(line);
      if (line.len() == 0) continue;
      if (line.len() < prefix.len()) continue;
      if (line.substr(0, prefix.len()-1) != prefix) continue;

      body = ssv_str_trim(line.substr(prefix.len(), line.len()-1));
      if (body.len() == 0) continue;
      eq = ssv_str_index(body, "=");
      if (eq < 0) continue;
      path = ssv_str_trim(body.substr(0, eq-1));
      val  = ssv_str_trim(body.substr(eq+1, body.len()-1));
      if (path.len() == 0) continue;

      // Split path on '.'.
      pstart = 0;
      for (pi = 0; pi < path.len(); pi++) begin
        if (path[pi] == ".") begin
          parts.push_back(path.substr(pstart, pi-1));
          pstart = pi + 1;
        end
      end
      parts.push_back(path.substr(pstart, path.len()-1));
      if (parts.size() == 0) continue;

      // Strip the root-class-name prefix (hierarchy may start with
      // <root_class_name>; the equivalent bare path is also accepted).
      root_name = root.get_name();
      if (parts[0] == root_name) begin
        keep = parts.size() - 1;
        for (i = 0; i < keep; i++) parts[i] = parts[i+1];
        parts.delete(keep);
      end
      if (parts.size() == 0) continue;

      `uvm_info("SSV_CFG", $sformatf("apply %s = %s", path, val), UVM_HIGH)
      root.dispatch_path(parts, val);
    end

    $fclose(fd);
  endfunction

  // --------------------------------------------------------------------
  // apply_overrides_in_cwd: the only function a test's build_phase needs
  // to call.
  //   Opens the relative path "cfg.info" (relies on cwd == case run dir,
  //   which run_case.py sets via subprocess.run).
  //   Python run_case.py already flattened every ssv_cfg: line into
  //   cfg.info -- the SV side does NOT read cases/*.cmd, plusargs, or
  //   env vars.
  // --------------------------------------------------------------------
  static function void apply_overrides_in_cwd(ssv_object root);
    `uvm_info("SSV_CFG", "reading cfg from ./cfg.info (cwd=case run dir)", UVM_LOW)
    apply_overrides_from_file(root, "cfg.info");
  endfunction

  // Legacy API compatibility: kept as an alias so older tests still compile.
  static function void apply_overrides(ssv_object root, string filename);
    apply_overrides_from_file(root, filename);
  endfunction

  // ====================================================================
  //                       string utility helpers
  // ====================================================================
  static function string ssv_str_trim(string s);
    int l;
    int r;
    l = 0;
    r = s.len() - 1;
    while (l <= r && (s[l] == " " || s[l] == "\t")) l++;
    while (r >= l && (s[r] == " " || s[r] == "\t")) r--;
    if (r < l) return "";
    return s.substr(l, r);
  endfunction

  static function string ssv_str_chomp(string s);
    string c;
    while (s.len() > 0) begin
      c = s[s.len() - 1];
      if (c == "\n" || c == "\r") s = s.substr(0, s.len() - 2);
      else break;
    end
    return s;
  endfunction

  static function int ssv_str_index(string s, string sub);
    int n;
    int m;
    int i;
    n = s.len();
    m = sub.len();
    if (m == 0) return -1;
    for (i = 0; i <= n - m; i++) begin
      if (s.substr(i, i + m - 1) == sub) return i;
    end
    return -1;
  endfunction

  // Strip surrounding double quotes (for ssv_cfg: FOO = "value").
  static function string ssv_unquote(string s);
    s = ssv_str_trim(s);
    if (s.len() >= 2 && s[0] == "\"" && s[s.len()-1] == "\"")
      return s.substr(1, s.len() - 2);
    return s;
  endfunction

  // Parse common numeric literals (decimal / 0 / 1 / 1'b0 / 1'b1).
  static function int ssv_atoi(string s);
    s = ssv_str_trim(s);
    if (s == "" || s == "0" || s == "1'b0") return 0;
    if (s == "1" || s == "1'b1") return 1;
    return s.atoi();
  endfunction

  // ====================================================================
  // ssv_ato_packed: parse an SV literal string into bit [255:0].
  //   Used for packed vector field / element assignment -- ssv_atoi would
  //   silently truncate to 32 bits.
  //   SV truncates the result to N bits when assigning to an N-bit field,
  //   so hex / bin literals are preserved.
  //
  //   Supported literal forms:
  //     "0" / "1" / "1'b0" / "1'b1"
  //     decimal digits ("123" / "-1")
  //     'h<hex> / 'd<dec> / 'b<bin> / 'o<oct>          (short form)
  //     <width>'h<hex> / <width>'d<dec> / etc.          (long form: re-parse
  //                                                     from the ' position)
  //
  //   Not supported: 'x / 'z, negative hex, spaces inside the literal.
  // ====================================================================
  static function bit [255:0] ssv_ato_packed(string s);
    bit [255:0] result;
    string tail;
    int    tick;
    string c;
    s = ssv_str_trim(s);
    result = '0;
    if (s == "" || s == "0" || s == "1'b0") return '0;
    if (s == "1" || s == "1'b1") return '1;

    // Short form: 'h / 'd / 'b / 'o
    if (s.len() >= 2 && s[0] == "'") begin
      if (s.len() == 1) return '0;       // bare "'" is not a valid literal
      c = s[1];
      tail = (s.len() >= 3) ? s.substr(2, s.len()-1) : "";
      case (c)
        "h", "H": return ssv_parse_hex(tail);
        "d", "D": return tail.atoi();
        "b", "B": return ssv_parse_bin(tail);
        "o", "O": return ssv_parse_oct(tail);
        default:  return s.atoi();
      endcase
    end

    // Long form: <width>'h... -- find the ' position and re-parse from there.
    for (tick = 0; tick < s.len(); tick++) begin
      if (s[tick] == "'") begin
        if (tick == s.len() - 1) return '0;   // trailing "'" is not valid
        return ssv_ato_packed(s.substr(tick, s.len()-1));
      end
    end

    // Default: decimal.
    return s.atoi();
  endfunction

  static function bit [255:0] ssv_parse_hex(string s);
    bit [255:0] r;
    bit [3:0]   nib;
    int         i;
    r = '0;
    for (i = 0; i < s.len(); i++) begin
      nib = 4'h0;
      case (s[i])
        "0":      nib = 4'h0;
        "1":      nib = 4'h1;
        "2":      nib = 4'h2;
        "3":      nib = 4'h3;
        "4":      nib = 4'h4;
        "5":      nib = 4'h5;
        "6":      nib = 4'h6;
        "7":      nib = 4'h7;
        "8":      nib = 4'h8;
        "9":      nib = 4'h9;
        "a", "A": nib = 4'ha;
        "b", "B": nib = 4'hb;
        "c", "C": nib = 4'hc;
        "d", "D": nib = 4'hd;
        "e", "E": nib = 4'he;
        "f", "F": nib = 4'hf;
        default:  ;
      endcase
      r = (r << 4) | nib;
    end
    return r;
  endfunction

  static function bit [255:0] ssv_parse_bin(string s);
    bit [255:0] r;
    int         i;
    r = '0;
    for (i = 0; i < s.len(); i++) begin
      r = r << 1;
      if (s[i] == "1") r[0] = 1'b1;
      // '0' / '_' / anything else: stay 0
    end
    return r;
  endfunction

  static function bit [255:0] ssv_parse_oct(string s);
    bit [255:0] r;
    bit [2:0]   digit;
    int         i;
    r = '0;
    for (i = 0; i < s.len(); i++) begin
      digit = 3'b0;
      case (s[i])
        "0": digit = 3'b000;
        "1": digit = 3'b001;
        "2": digit = 3'b010;
        "3": digit = 3'b011;
        "4": digit = 3'b100;
        "5": digit = 3'b101;
        "6": digit = 3'b110;
        "7": digit = 3'b111;
        default: ;
      endcase
      r = (r << 3) | digit;
    end
    return r;
  endfunction

endclass

`endif // SSV_OBJECT_SV
